# /.golangci.yml
run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - revive
    - misspell
    - gofumpt
    - depguard
    - gocyclo
linters-settings:
  gofumpt:
    extra-rules: true
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: indent-error-flow
      - name: errorf
      - name: receiver-naming
      - name: time-naming
  depguard:
    rules:
      main:
        files:
          - $all
        list-mode: lax
        allow:
          - $gostd
          - github.com
          - golang.org
          - gopkg.in
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - gofumpt
    - linters:
        - errcheck
      text: "Close.*error"
