name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-amd64:
    name: linux-amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.23.x, 1.22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - run: make tidy
      - run: make fmt
      - run: make strip
      - run: make lint
      - run: make vet
      - run: make test-race
      - run: make cover
        env:
          MINCOV: 95
      - run: make build
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.go }}
          path: .build/coverage.out

  build-only:
    name: build-only
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - run: make build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

  terraform-fmt:
    name: Terraform fmt equivalence
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - run: go test ./internal/fmt -run TestGoMatchesBinary
