name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [stable, oldstable]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - run: make tidy
      - run: make fmt
      - run: make nocomments
      - run: make lint
      - run: make vet
      - name: Vulnerability check
        run: make vuln
        continue-on-error: true
      - run: make test-race
      - run: make cover
        env:
          COVER_THRESH: 95
      - run: make build

  terraform-fmt:
    name: Terraform fmt equivalence
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - run: go test ./internal/fmt -run TestGoMatchesBinary
