name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.23.x, 1.22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - run: make tidy
      - run: make fmt
      - run: make lint
      - name: Fuzz tests
        run: go test ./... -run=^$ -fuzz=Fuzz -fuzztime=5s
        continue-on-error: true
      - name: Vulnerability check
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
        continue-on-error: true
      - run: make test-race
      - run: make cover
        env:
          COVER_THRESH: 95
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.go }}
          path: .build/coverage.out
      - run: make build

  terraform-fmt:
    name: Terraform fmt equivalence
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - run: go test ./internal/fmt -run TestGoMatchesBinary
