name: Go

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [stable, oldstable]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Download modules
        run: go mod download

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          # Pin a known-good version for reproducibility; update as needed.
          version: v1.60.3
          args: --timeout=5m

      - name: Vet
        run: go vet ./...

      - name: Vulnerability check (non-blocking)
        continue-on-error: true
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Test
        run: go test -race -shuffle=on -covermode=atomic -coverprofile=coverage.out ./...

      - name: Check coverage
        run: |
          go tool cover -func=coverage.out
          total=$(go tool cover -func=coverage.out | grep ^total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: ${total}%"
          awk -v total="$total" 'BEGIN {if (total+0 < 95.0) {printf "Coverage %.1f%% is below 95%%\n", total; exit 1}}'

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.go }}
          path: coverage.out

      - name: Build
        run: go build -o hclalign ./...

      - name: Idempotency check
        run: |
          find tests/cases -name out.tf -print0 \
            | xargs -0 -n1 ./hclalign --check

      - name: Upload release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: hclalign-${{ matrix.os }}-${{ matrix.go }}
          path: hclalign
